fix type error: Argument 2 passed to Invoice\Services\InvoiceLimitati…
plentymarkets/plugin-payment-invoice pull request #20
Opened 2020-03-13 09:09 UTC by danielmarx

@plentymarkets/team-order-payment 

Problem:
"Type error: Argument 2 passed to Invoice\Services\InvoiceLimitationsService::respectsAllLimitations() must be of the type int, null given, called in plugins/sets/36/builds/c087281096ee7ba2cc6a6e684bf45ca7/Invoice/src/Methods/InvoicePaymentMethod.php on line 91

https://plentymarkets.kanbanize.com/ctrl_board/50/cards/98822/details/

2020-03-13 10:44 UTC, raphael-adam commented
Ich kann nachher nochmal testen, ob ich das Problem noch lokal habe und ob der Fix es behebt. Es fehlt aber noch Version + Changelog.

2020-03-13 12:05 UTC, raphael-adam approved these changes
Kann es lokal leider nicht mehr nachstellen.

2020-03-13 13:37 UTC, CTohme reviewed
Versionsupdate und Changelog fehlen noch.
(Falls sichergestellt ist, dass bei den anderen Parametern keine Fehler auftreten können, dann würde ich sagen i.O.)

2020-03-17 08:12 UTC, estafilarakis requested changes
Das ist für mich keine Lösung. Ein `int` Cast von `NULL` ergibt die ID 0, was kein gültiges Land ist!
Dann lieber pauschal 1 für Deutschland nehmen.

2020-03-17 08:12 UTC, estafilarakis commented on src/Methods/InvoicePaymentMethod.php
> +            (INT) $this->checkout->getShippingCountryId(),
```suggestion
            $this->checkout->getShippingCountryId() ?? 1,
```

2020-03-17 08:12 UTC, estafilarakis commented on src/Methods/InvoicePaymentMethod.php
> +                (INT) $this->checkout->getShippingCountryId(),
```suggestion
                $this->checkout->getShippingCountryId() ?? 1,
```

2020-03-19 07:06 UTC, estafilarakis approved these changes

2020-03-19 08:10 UTC, raphael-adam approved these changes

2020-03-31 06:54 UTC, merged